apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-world-ui.fullname" . }}
  labels:
    app: {{ template "hello-world-ui.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.externalPort }}
      targetPort: {{ .Values.ui.image.internalPort }}
      name: {{ .Values.ui.service.name }}
  selector:
    app: {{ template "hello-world-ui.fullname" . }}
    release: {{ .Release.Name }}