name: hello-world-app
version: 0.2.1
description: Hello world sample app to demonstrate deployment capabilities
keywords:
  - alfresco
  - anaxes
  - hello
  - world
home: https://github.com/Alfresco/alfresco-anaxes-hello-world/app-deployment/helm
sources:
  - https://github.com/Alfresco/alfresco-anaxes-hello-world/app-deployment/helm
maintainers:
  - name: Alfresco
