dependencies:
  - name: hello-world-service
    version: ^0.1
    repository: https://alfresco.github.io/charts-test/incubator
  - name: hello-world-ui
    version: ^0.1
    repository: https://alfresco.github.io/charts-test/incubator
