# Default values for hello-world-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
registryPullSecrets: quay-registry-secret

ui:
  image:
    repository: quay.io/alfresco/alfresco-sample-app-ui
    tag: 0.1-SNAPSHOT
    pullPolicy: Always
    internalPort: 80
  service:
    name: hello-world-app-ui
    # If running on AWS choose LoadBalancer as service Type
    type: NodePort
    externalPort: 80
  ingress:
    path: /hello-ui
  api:
    # These may need to be overridden when deploying
    url: hello-service
