dependencies:
  - name: hello-world-service
    version: ^0.1
    repository: file://../../../service-deployment/charts/hello-world-service
  - name: hello-world-ui
    version: ^0.1
    repository: file://../../../ui-deployment/charts/hello-world-ui
